type FilterTypes = number | boolean | string;

interface FiltersState {
    [index: string]: FilterTypes;
    brightness: number;
    contrast: number;
    saturate: number;
    greyscale: number;
    redGreyscale: boolean;
    greenGreyscale: boolean;
    blueGreyscale: boolean;
    purplescale: boolean;
    twenties: boolean;
    whiteNoise: boolean;
    whiteNoiseVal: number;
    blackNoise: boolean;
    blackNoiseVal: number;
    customNoise: boolean;
    customNoiseVal: number;
    customNoiseColor: string;
    specksredscale: boolean;
    greenSpecks: boolean;
    redCasino: boolean;
    yellowCasino: boolean;
    matrix: boolean;
    eclectic: boolean;
    cosmic: boolean;
    retroviolet: boolean;
    confetti: boolean;
    rgbSplit: boolean;
    offsetRed: boolean;
    offsetRedVal: number;
    offsetGreen: boolean;
    offsetGreenVal: number;
    offsetBlue: boolean;
    offsetBlueVal: number;
    invert: boolean;
    neue: boolean;
    lix: boolean;
    ryo: boolean;
    solange: boolean;
    coolTwilight:boolean;
    mellow: boolean;
    eon: boolean;
    aeon: boolean;
    redEffect: boolean;
    perfume: boolean;
    serenity: boolean;
    pinkAura: boolean;
    radio: boolean;
    sepia: number;
    blur: number;
    opacity: number;
    bkgColor: boolean;
    bkgColorVal: string;
    hueRotate: number;
    frontward: boolean;
    gamma: boolean;
    gammaVal: number;
    redGamma: boolean;
    greenGamma: boolean;
    yellowGamma: boolean;
    purpleGamma: boolean;
    blueRedGamma: boolean;
    blueGreenGamma: boolean;
    diagonalLines: boolean;
    crimson: boolean;
    lemon: boolean;
    vintage: boolean;
    haze: boolean;
    horizon: boolean;
    grime: boolean;
    threshold: boolean;
    thresholdVal: number;
    sobel: boolean;
    pixelate: boolean;
    pixelateVal: number;
};

// Note: the order of the properties below can affect how the filters interact with each other.
const initialFiltersState: FiltersState = {
    brightness: 1,
    contrast: 1,
    saturate: 1,
    threshold: false,
    thresholdVal: 100,
    sobel: false,
    greyscale: 0,
    redGreyscale: false,
    greenGreyscale: false,
    blueGreyscale: false,
    purplescale: false,
    twenties: false,
    whiteNoise: false,
    whiteNoiseVal: 15,
    blackNoise: false,
    blackNoiseVal: 15,
    customNoise: false,
    customNoiseVal: 15,
    customNoiseColor: "#ff0000",
    specksredscale: false,
    greenSpecks: false,
    redCasino: false,
    yellowCasino: false,
    matrix: false,
    eclectic: false,
    cosmic: false,
    retroviolet: false,
    confetti: false,
    rgbSplit: false,
    offsetRed: false,
    offsetRedVal: 5,
    offsetGreen: false,
    offsetGreenVal: 5,
    offsetBlue: false,
    offsetBlueVal: 5,
    invert: false,
    neue: false,
    lix: false,
    ryo: false,
    solange: false,
    coolTwilight: false,
    mellow: false,
    eon: false,
    aeon: false,
    redEffect: false,
    perfume: false,
    serenity: false,
    pinkAura: false,
    radio: false,
    sepia: 0,
    blur: 0,
    opacity: 1,
    bkgColor: false,
    bkgColorVal: "#0000ff",
    hueRotate: 0,
    frontward: false,
    gamma: false,
    gammaVal: 2,
    redGamma: false,
    greenGamma: false,
    yellowGamma: false,
    purpleGamma: false,
    blueRedGamma: false,
    blueGreenGamma: false, // aka Teal
    diagonalLines: false,
    crimson: false,
    lemon: false,
    vintage: false,
    haze: false,
    horizon: false,
    grime: false,
    pixelate: false,
    pixelateVal: 10
};

export { FilterTypes, FiltersState, initialFiltersState }